version: '3'
services:
    web:
        image: nginx
        container_name: stamboom_web
        volumes:
            - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./.docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params"
            - "./server:/var/www/html"
        ports:
            - "8000:80"
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
            - angular

    angular:
        image: node:8
        container_name: stamboom_angular
        volumes:
            - ./client:/var/www/stamboom
        ports:
            - "80:4200" 
            - "49153:49153"
        command: /bin/bash -c "npm i -g @angular/cli && cd /var/www/stamboom && npm i && ng serve --host 0.0.0.0"

    php:
        image: nanoninja/php-fpm:7.1
        container_name: stamboom_php
        restart: always
        volumes:
            - "/opcache"
            - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./server:/var/www/html"
            - "./.docker/config/db.php:/var/www/html/config/db.php"
            - "./.docker/config/db_admin.php:/var/www/html/config/db_admin.php"

    composer:
        image: composer
        container_name: stamboom_composer
        volumes:
            - "./server:/app"
        command: install --ignore-platform-reqs

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: stamboom_phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=stamboom_mysql
        restart: always
        depends_on:
            - mysqldb

    mysqldb:
        image: mysql:5.7
        container_name: stamboom_mysql
        restart: always
        environment:
            - MYSQL_DATABASE=stamboom
            - MYSQL_ROOT_PASSWORD=verysecret
            - MYSQL_USER=user
            - MYSQL_PASSWORD=verysecret
        ports:
            - "8989:3306"
        volumes:
            - "./.docker/data/db/mysql:/var/lib/mysql:cached"
            - "./.docker/sql:/docker-entrypoint-initdb.d/"
            - "./.docker/mysql/sqlmode.cnf:/etc/mysql/conf.d/sqlmode.cnf"